### ISSUE TITLE
Jak si muzu objednat automobil? (nefujguje)

### ISSUE THREAD

**Issue by calcium6** [skrilexxx/CarRental#1]
![20240108_180351](https://github.com/skrilexxx/CarRental/assets/62720375/5178f59f-8dc2-41c9-8bef-5551da7de63f)

**Comment by skrilexxx** [comment]
https://www.brnocarrental.cz/

**Comment by calcium6** [comment]
![Screenshot_20240112_141334_Chrome.png](https://github.com/skrilexxx/CarRental/assets/62720375/752c38f2-b03b-4e64-9fd4-44b61b739212)

Nefunguje vyhledávání

**Comment by skrilexxx** [comment]
pracuju na tom sefe

**Comment by skrilexxx** [comment]
už to funguje, je to UPPPP
https://www.brnocarrental.cz/
